### PR TITLE
Colors!!!

### LINKED ISSUE #125: Primary Button is not accessible
## Issue Type
Bug Report

## Component or Pattern Affected
Button

## Expected Behavior
Colors should be accessible to all users

## Current Behavior

Primary Button is not accessible according to AA or AAA standards

## Possible Solution

Black (dark) color instead of white(light) color for the primary button is accessible

## Steps to Reproduce (for bugs)
Screen Shot 2019-03-14 at 11 11 50 AM

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

### LINKED ISSUE #148: [Avatar] Self avatar does not have proper color
When using the react component as follows, the rendered component does not have the "blue" color:

```jsx
<Avatar type="self" />
```

## Issue Type
Bug Report

## Component or Pattern Affected
React Avatar

## Expected Behavior
image

## Current Behavior
image

## Your Environment

* Library: React
* Version used: 12.0.3
* Browser Name and version: Chrome
* Operating System and version: macOS

### LINKED ISSUE #167: Schematics folder is not bundled in @collab-ui/angular@5.0.0
## Issue Type
Bug Report 

## Component or Pattern Affected
Schematics folder is not included in the npm package, which throws the error when you run `ng add @collab-ui/angular`

```
Error: Collection "@collab-ui/angular" cannot be resolved.
```
## Expected Behavior

The command `ng add @collab-ui/angular` should add collab ui to any Angular CLI project

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

### LINKED ISSUE #168: [Angular]: Move lodash-es to Peer Dependencies
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

### PR DESCRIPTION
**Pull request by pauljeter**
## Description
Updating the color palette and adding Tokens

## Related Issue
Fixes #125 
Fixes #168 
Fixes #167 
Fixes #148 

## Motivation and Context
Add color tokens to enable more apps and platforms to consume the Momentum Design color palette https://momentum.design/styles/color

## Screenshots:
dev-collab-ui cisco com_playground

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update
- [x] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: angular/src/lib/select/select.component.ts [hunk 1]
```diff
@@ -47,19 +57,19 @@ interface IState {
...
       <cui-list>
         <ng-content></ng-content>
       </cui-list>
     </ng-template>
   `,
   styles: [],
   host: {
-    class: 'cui-input-group cui-select'
-  }
+    class: 'cui-input-group cui-select',
```
Comment (mathsusan) [inline angular/src/lib/select/select.component.ts]: comma is needed here?

Comment (pauljeter) [reply angular/src/lib/select/select.component.ts]: Not needed, but we prefer dangling commas for git diffs. This one got added because I auto-formatted the file before saving.

File: core/scss/colors/utilities.scss [hunk 2]
```diff
@@ -0,0 +1,391 @@
...
+.cui-color--blue-10 { color: #E6F9FC !important; }
+.cui-color--blue-20 { color: #B8F2FF !important; }
+.cui-color--blue-30 { color: #73E3FF !important; }
+.cui-color--blue-40 { color: #1DC4F2 !important; }
+.cui-color--blue-50 { color: #00A0D1 !important; }
+.cui-color--blue-60 { color: #007EA8 !important; }
+.cui-color--blue-70 { color: #0A5E7D !important; }
+.cui-color--blue-80 { color: #124052 !important; }
+.cui-color--blue-90 { color: #122933 !important; }
+.cui-color--blue-100 { color: #101C21 !important; }
```
Comment (daanishnasir) [inline core/scss/colors/utilities.scss]: Do we want to keep cui-color--blue with theme being the same.

File: angular/src/lib/examples.module.ts [hunk 3]
```diff
@@ -43,8 +43,8 @@ import { DatePickerExamplesModule } from './date-picker/examples/examples.module
     ToggleSwitchExamplesModule,
     EditableTextfieldExamplesModule,
     TopbarExamplesModule,
-    TimePickerExamplesModule,
-    DatePickerExamplesModule
+    // TimePickerExamplesModule,
```
Comment (bfbiggs) [inline angular/src/lib/examples.module.ts]: Meant to be commented out?

File: core/app/styles.scss [hunk 4]
```diff
@@ -4,7 +4,7 @@ $images-path: '~@collab-ui/core/images';
 @import '~@collab-ui/core/scss/collab-ui';
 $side-nav-width: 240px;
 body {
-  background: $white;
+  background: $cui-white-100;
```
Comment (bfbiggs) [inline core/app/styles.scss]: Just a thought - should we prefix this with a variable in preparation for the md switch?

Comment (pauljeter) [reply core/app/styles.scss]: Let's discuss for a future feature

File: angular/src/lib/examples.module.ts (hunk 3 above)
Comment (pauljeter) [reply angular/src/lib/examples.module.ts]: Yes, we need a separate PR to fix the issue with these components.

File: core/scss/colors/utilities.scss (hunk 2 above)
Comment (pauljeter) [reply core/scss/colors/utilities.scss]: Yes

File: core/scss/components/avatar/avatar.scss [hunk 5]
```diff
@@ -90,7 +90,7 @@
 
       background-color: $avatar-self__background;
       border: $avatar-self__border;
-      fill: $avatar-self__color;
+      color: $avatar-self__color;
```
Comment (adamweeks) [inline core/scss/components/avatar/avatar.scss]: img
